name: Code Analysis (ESLint)

on:
  push:
    branches:
      - Experimental
      - master

  pull_request:
    branches:
      - Experimental
      - master

jobs:
  ESLint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install SARIF Formatter
        run: npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        run: npx eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
